#!/usr/bin/env python3
"""Independent arithmetic audit. Imports neither producer nor closure library.

Finite sources are rebuilt by head choices; quotient checks use coset reduction
rather than the producer's annihilator projection. All arithmetic is integral
or fractions.Fraction; assertions are not used as verification gates.
"""
from __future__ import annotations
import argparse,copy,gzip,json
from collections import Counter
from fractions import Fraction as F
from hashlib import sha256
from itertools import product,permutations,combinations
from pathlib import Path

def check(ok,msg):
    if not ok:raise ValueError(msg)

def minus(x,y):return tuple(a-b for a,b in zip(x,y))
def pair(x,y):return sum(a*b for a,b in zip(x,y))
def isroot(x):return sorted(x)==[-1]+[0]*(len(x)-2)+[1]

def source(n,E):
    out={}
    for choices in product((0,1),repeat=len(E)):
        v=[0]*n
        for edge,c in zip(E,choices):v[edge[c]]+=1
        mask=sum(c<<j for j,c in enumerate(choices))
        out.setdefault(tuple(v),[]).append(mask)
    return {v:sorted(m) for v,m in out.items()}

def score(mask,n,E):
    out=[0]*n
    for j,e in enumerate(E):out[e[(mask>>j)&1]]+=1
    return tuple(out)

def reduce_basis(rows,n):
    out=[];piv=[]
    for row in rows:
        a=list(map(F,row))
        for j,b in zip(piv,out):
            q=a[j];a=[x-q*y for x,y in zip(a,b)]
        j=next((h for h,x in enumerate(a) if x),None)
        if j is None:continue
        q=a[j];a=[x/q for x in a]
        # Earlier pivots need not be reduced at this new pivot for remainder use.
        out.append(a);piv.append(j)
    return out,piv

def remainder(v,rows):
    a=list(map(F,v));base,piv=reduce_basis(rows,len(v))
    for j,row in zip(piv,base):
        q=a[j];a=[x-q*y for x,y in zip(a,row)]
    return tuple(a)

def inspan(v,rows):return not any(remainder(v,rows))
def expression(v,rows,c):
    c=list(map(F,c))
    return len(c)==len(rows) and all(sum(q*w[i] for q,w in zip(c,rows))==v[i] for i in range(len(v)))

def noap(P,k):
    ordered=sorted(set(P));S=set(ordered)
    for i,a in enumerate(ordered):
        for b in ordered[i+1:]:
            d=minus(b,a)
            if all(tuple(x+j*y for x,y in zip(a,d)) in S for j in range(2,k)):return False
    return True

def validate_packet(p,r,S,E):
    n=len(r);a=p['anchor'];v=p['step'];ss=p['switch'];xs=p['scores']
    check(len(ss)==len(xs)==5,'packet length')
    check(all(s in (0,1) for s in ss),'unsupported switch')
    check(ss[0]==0,'packet anchor convention')
    for i,(sw,x) in enumerate(zip(ss,xs)):
        check(tuple(x) in S,'absent orientation score')
        check(tuple(x)==tuple(a[j]+i*v[j]+sw*r[j] for j in range(n)),'packet equation')
        check(score(p['orientation_masks'][i],n,E)==tuple(x),'wrong original orientation mask')
    return True

def symmetry_orbit(r):
    out=set()
    for a in permutations(range(3)):
      for b in permutations(range(3,6)):
       for pp in (a+b,b+a):
        for sign in (1,-1):out.add(tuple(sign*r[i] for i in pp))
    return out

def validate_orbits(rows,S,E):
    differences={minus(x,y) for x in S for y in S}-{(0,)*6};covered=set();types=Counter()
    for row in rows:
        r=tuple(row['difference']);check(r in differences,'unsupported initial difference')
        orb=symmetry_orbit(r);check(not covered&orb,'repeated orbit');check(len(orb)==row['orbit_size'],'orbit cardinality')
        covered|=orb;types[row['kind']]+=1
        for p in row['packets']:validate_packet(p,r,S,E)
        if row['kind']=='divided-local':
            check(row['retained_factor']==2,'wrong retained scalar')
            h=tuple(row['local_difference']);v=row['packets'][0]['step']
            check(tuple(2*x for x in h)==r,'unjustified local division')
            check(tuple(-2*x for x in v)==r,'missing collapse alternative')
            validate_packet(row['auxiliary_local_packet'],h,S,E)
            check(isroot(row['auxiliary_local_packet']['step']),'invalid local exit')
        else:
            rho=tuple(row['root']);check(isroot(rho),'not an actual root')
            vs=[p['step'] for p in row['packets']]
            check(expression(rho,vs,row['combination']),'root not generated by displayed steps')
    check(covered==differences,'difference orbit coverage incomplete')
    return dict(types)

def validate_tensor(rows,S,E):
    total=0
    for case in rows:
        marks=case['marks'];h=len(marks);weights=[[abs(t[v]-t[u]) for u,v in E] for t in marks]
        check(weights==case['weights'],'changed generator values')
        flat=sum(weights,[]);check(min(flat)>0 and len(flat)==len(set(flat)),'nonpositive/repeated generators')
        check(sum(pair(t,minus(y,x)) for t,x,y in zip(marks,case['left'],case['right']))==0,'lost input collision')
        values=[]
        for xx,mm in zip(case['score_tuples'],case['subset_masks']):
            check(len(xx)==len(mm)==h,'tensor width')
            for x in xx:check(tuple(x) in S,'tensor source left score product')
            value=sum(sum(w for j,w in enumerate(ww) if (mask>>j)&1) for ww,mask in zip(weights,mm))
            reflected=sum(sum(max(t[u],t[v]) for u,v in E)-pair(t,x) for t,x in zip(marks,xx))
            check(value==reflected,'source/subset square failed')
            values.append(value)
        check(values==case['values'],'incorrect witness values')
        d=values[1]-values[0];check(d==case['step'] and d!=0,'zero witness step')
        check(all(v==values[0]+j*d for j,v in enumerate(values)),'witness is not an AP');total+=1
    return total

def validate_closures(rows):
    models=0;barriers=Counter();rounds=Counter()
    for row in rows:
        n=row['n'];k=row['k'];S=list(product((0,1),repeat=n));W=[tuple(v) for v in row['initial']]
        initial_rank=len(reduce_basis(W,n)[0]);seen=0
        for rr in row['rounds']:
            check([tuple(x) for x in rr['original_basis']]==W,'closure basis changed without certificate')
            old=list(W)
            for step in rr['steps']:
                xs=step['points'];v=tuple(step['step']);check(len(xs)==k and all(tuple(x) in S for x in xs),'unsupported AP row')
                check(v==minus(xs[1],xs[0]),'wrong derived step')
                check(not inspan(v,W),'non-progressing derivation')
                for i in range(k-2):
                    dd=tuple(xs[i][j]-2*xs[i+1][j]+xs[i+2][j] for j in range(n))
                    check(dd==tuple(step['defects'][i]),'altered defect')
                    check(expression(dd,old,step['premise_coefficients'][i]),'unproved closure premise')
                W.append(v);seen+=1
        check(W==[tuple(x) for x in row['closed_basis']],'missing closure step')
        check(seen<=n-initial_rank,'rank certificate exceeded')
        P={remainder(x,W) for x in S};check(noap(P,k),'proposed quotient is not closed')
        model=row['model']
        if model is None:
            b=row['infeasibility'];v=b['vector'];check(expression(v,W,b['coefficients']),'invalid infeasibility implication')
            if b['kind']=='forced-equality':check(isroot(v),'false equal-coordinate obstruction')
            else:check(b['kind']=='positive-obstruction' and min(v)>=0 and any(v),'false positivity obstruction')
            barriers[b['kind']]+=1
        else:
            a=model['weights'];check(min(a)>0 and len(set(a))==n,'invalid realized weights')
            check(all(pair(a,v)==0 for v in W),'observer does not kill closure')
            for x in S:
              for y in S:
                v=minus(x,y);check((pair(a,v)==0)==inspan(v,W),'finite value kernel lost')
                for z in S:
                    v=tuple(x[j]-2*y[j]+z[j] for j in range(n))
                    check((pair(a,v)==0)==inspan(v,W),'second-difference transport lost')
            check(noap({(pair(a,x),) for x in S},k),'integer realization is not admissible');models+=1
        rounds[seen]+=1
    return {'cases':len(rows),'positive_distinct_models':models,'infeasibility':dict(barriers),'strict_derived_steps':dict(rounds)}

def validate_moments(record,S,E):
    X=sorted(S);m=len(X);n=len(X[0]);means=[F(sum(x[i] for x in X),m) for i in range(n)]
    C=[[sum((F(x[i])-means[i])*(F(x[j])-means[j]) for x in X)/m for j in range(n)] for i in range(n)]
    check(record['cardinality']==m,'wrong source count')
    check(record['word_count']==sum(map(len,S.values())),'wrong word count')
    check([[str(x) for x in row] for row in C]==record['covariance'],'wrong unweighted covariance')
    counts={str(k):v for k,v in sorted(Counter(map(len,S.values())).items())}
    check(counts==record['multiplicity_histogram'],'multiplicities were collapsed')
    for i in range(n):
      for j in range(n):
        lap=sum(i in e for e in E) if i==j else -sum(set(e)=={i,j} for e in E)
        expected=F(25,76)*lap if n==4 else F(25,82)*lap-F((1 if i<3 else -1)*(1 if j<3 else -1),164)
        check(C[i][j]==expected,'covariance/Laplacian identity failed')

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--proof',type=Path,default=Path(__file__).with_name('proof_data.json.gz'));ap.add_argument('--output',type=Path,default=Path(__file__).with_name('independent_audit.json'));args=ap.parse_args()
    raw=gzip.decompress(args.proof.read_bytes());data=json.loads(raw)
    E=[(i,j) for i in range(3) for j in range(3,6)];S=source(6,E);E4=list(combinations(range(4),2));S4=source(4,E4)
    check({tuple(x['score']):x['masks'] for x in data['source_K33']['scores']}==S,'source fibres differ')
    types=validate_orbits(data['K33_orbits'],S,E)
    R4={minus(x,y) for x in S4 for y in S4}-{(0,)*4}
    check({tuple(x['difference']) for x in data['K4_packets']}==R4,'K4 coverage')
    for row in data['K4_packets']:
        validate_packet(row['packet'],row['difference'],S4,E4);check(isroot(row['packet']['step']),'K4 wrong root')
    tensors=validate_tensor(data['tensor_cases'],S,E)
    cr=validate_closures(data['closure_records'])
    validate_moments(data['moments']['K33'],S,E);validate_moments(data['moments']['K4'],S4,E4)
    mutants=[]
    row=copy.deepcopy(data['K33_orbits'][0]);row['packets'][0]['orientation_masks'][0]^=1
    mutants.append(('wrong orientation',lambda:validate_packet(row['packets'][0],row['difference'],S,E)))
    rows=copy.deepcopy(data['K33_orbits']);rows.pop();mutants.append(('missing orbit',lambda:validate_orbits(rows,S,E)))
    rows2=copy.deepcopy(data['K33_orbits']);next(r for r in rows2 if r['kind']=='two-switch')['combination']=[0,0]
    mutants.append(('discarded step relation',lambda:validate_orbits(rows2,S,E)))
    rows3=copy.deepcopy(data['K33_orbits']);next(r for r in rows3 if r['kind']=='divided-local')['retained_factor']=3
    mutants.append(('false local saturation',lambda:validate_orbits(rows3,S,E)))
    moment=copy.deepcopy(data['moments']['K33']);moment['covariance'][0][1]='0'
    mutants.append(('discarded cross covariance',lambda:validate_moments(moment,S,E)))
    ten=copy.deepcopy(data['tensor_cases'][:1]);ten[0]['values'][2]+=1
    mutants.append(('false integer progression',lambda:validate_tensor(ten,S,E)))
    clo=copy.deepcopy(next(r for r in data['closure_records'] if r['rounds']));clo['rounds'][0]['steps'][0]['premise_coefficients'][0]=[]
    mutants.append(('unsupported closure premise',lambda:validate_closures([clo])))
    bad=copy.deepcopy(next(r for r in data['closure_records'] if r['model']));bad['model']['weights'][0]=0
    mutants.append(('nonpositive realization',lambda:validate_closures([bad])))
    rejected=[]
    for label,fn in mutants:
        try:fn()
        except (ValueError,IndexError,KeyError,TypeError):rejected.append(label)
        else:raise ValueError('mutant escaped: '+label)
    out={'schema':'ep817-defect-closure-independent-audit-v1','status':'PASS','lean_checked':False,
         'K33_orientation_masks':512,'K33_distinct_scores':len(S),'K33_nonzero_differences':5298,
         'orbit_certificates':len(data['K33_orbits']),'orbit_types':types,
         'K4_differences':len(R4),'tensor_witness_cases':tensors,'closure':cr,
         'mutation_controls_rejected':rejected,'auditor_sha256':sha256(Path(__file__).read_bytes()).hexdigest(),
         'proof_sha256':sha256(raw).hexdigest(),
         'scope':'Finite arithmetic audit; the unrestricted-rank tensor and closure conclusions use the written proofs.'}
    args.output.write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps(out,sort_keys=True,indent=2))
if __name__=='__main__':main()
