import Mathlib

/-!
# Certified core of the proposed `k = 4` rate construction for Erdős Problem 817

This module certifies three exact pieces used by the written proof:

1. the bounded kernel of `(u,v,w) ↦ u + 7v + 8w` modulo `19`;
2. the absence of nonconstant four-term progressions in the seven-digit set;
3. the recursive least-digit lifting from that modular statement to arbitrarily
   many base-19 blocks.

It also certifies the algebraic relation-splitting morphism used in the lower
bound.  The finite theorems use kernel-checked `decide`; the recursive lifting and
relation-splitting arguments are proved symbolically for all lengths.
-/

namespace ErdosProblem817

/-- The seven subset-sum digits generated by the block `{1,7,8}`. -/
def digitValue : Fin 7 → ℤ
  | 0 => 0
  | 1 => 1
  | 2 => 7
  | 3 => 8
  | 4 => 9
  | 5 => 15
  | 6 => 16

/-- The five allowed coefficients, encoded without an interval coercion. -/
def coefficientValue : Fin 5 → ℤ
  | 0 => -2
  | 1 => -1
  | 2 => 0
  | 3 => 1
  | 4 => 2

/-- Exact finite bounded-kernel certificate for the block `(1,7,8)`. -/
theorem bounded_kernel_mod19 :
    ∀ u v w : Fin 5,
      (19 : ℤ) ∣
          (coefficientValue u + 7 * coefficientValue v +
            8 * coefficientValue w) ↔
        coefficientValue u = coefficientValue v ∧
          coefficientValue w = -coefficientValue u := by
  decide

/-- Divisibility form of the exact second-difference rigidity of the digit set. -/
theorem digit_second_difference_rigidity :
    ∀ a₀ a₁ a₂ a₃ : Fin 7,
      (19 : ℤ) ∣
          (digitValue a₀ - 2 * digitValue a₁ + digitValue a₂) →
      (19 : ℤ) ∣
          (digitValue a₁ - 2 * digitValue a₂ + digitValue a₃) →
      digitValue a₀ = digitValue a₁ ∧
        digitValue a₁ = digitValue a₂ ∧
        digitValue a₂ = digitValue a₃ := by
  decide

/-- A base-19 word, stored from its least significant digit upward. -/
inductive Language : Nat → ℤ → Prop
  | zero : Language 0 0
  | cons {m : Nat} {x : ℤ} (d : Fin 7) (hx : Language m x) :
      Language (m + 1) (digitValue d + 19 * x)

theorem Language.succ_coordinates {m : Nat} {x : ℤ}
    (hx : Language (m + 1) x) :
    ∃ d : Fin 7, ∃ y : ℤ,
      Language m y ∧ x = digitValue d + 19 * y := by
  cases hx with
  | cons d hy => exact ⟨d, _, hy, rfl⟩

/-- Two vanishing second differences encode an ordered four-term progression. -/
def FourTermProgression (x₀ x₁ x₂ x₃ : ℤ) : Prop :=
  x₀ - 2 * x₁ + x₂ = 0 ∧ x₁ - 2 * x₂ + x₃ = 0

/-- Every four-term progression in the length-`m` language is constant. -/
theorem language_four_ap_constant :
    ∀ m : Nat, ∀ x₀ x₁ x₂ x₃ : ℤ,
      Language m x₀ → Language m x₁ → Language m x₂ → Language m x₃ →
      FourTermProgression x₀ x₁ x₂ x₃ →
      x₀ = x₁ ∧ x₁ = x₂ ∧ x₂ = x₃ := by
  intro m
  induction m with
  | zero =>
      intro x₀ x₁ x₂ x₃ h₀ h₁ h₂ h₃ _
      cases h₀
      cases h₁
      cases h₂
      cases h₃
      exact ⟨rfl, rfl, rfl⟩
  | succ m ih =>
      intro x₀ x₁ x₂ x₃ h₀ h₁ h₂ h₃ hap
      obtain ⟨d₀, y₀, hy₀, rfl⟩ := h₀.succ_coordinates
      obtain ⟨d₁, y₁, hy₁, rfl⟩ := h₁.succ_coordinates
      obtain ⟨d₂, y₂, hy₂, rfl⟩ := h₂.succ_coordinates
      obtain ⟨d₃, y₃, hy₃, rfl⟩ := h₃.succ_coordinates
      rcases hap with ⟨hap₀, hap₁⟩
      have hdiv₀ : (19 : ℤ) ∣
          (digitValue d₀ - 2 * digitValue d₁ + digitValue d₂) := by
        refine ⟨-(y₀ - 2 * y₁ + y₂), ?_⟩
        linarith
      have hdiv₁ : (19 : ℤ) ∣
          (digitValue d₁ - 2 * digitValue d₂ + digitValue d₃) := by
        refine ⟨-(y₁ - 2 * y₂ + y₃), ?_⟩
        linarith
      obtain ⟨hd₀₁, hd₁₂, hd₂₃⟩ :=
        digit_second_difference_rigidity d₀ d₁ d₂ d₃ hdiv₀ hdiv₁
      have hyap₀ : y₀ - 2 * y₁ + y₂ = 0 := by
        rw [hd₀₁, hd₁₂] at hap₀
        linarith
      have hyap₁ : y₁ - 2 * y₂ + y₃ = 0 := by
        rw [hd₁₂, hd₂₃] at hap₁
        linarith
      obtain ⟨hy₀₁, hy₁₂, hy₂₃⟩ :=
        ih y₀ y₁ y₂ y₃ hy₀ hy₁ hy₂ hy₃ ⟨hyap₀, hyap₁⟩
      constructor
      · rw [hd₀₁, hy₀₁]
      constructor
      · rw [hd₁₂, hy₁₂]
      · rw [hd₂₃, hy₂₃]

/-- One block choice consists of three independent binary generator choices. -/
abbrev BlockChoice := Fin 3 → Bool

def bitValue (b : Bool) : ℤ := if b then 1 else 0

def blockValue (e : BlockChoice) : ℤ :=
  bitValue (e 0) + 7 * bitValue (e 1) + 8 * bitValue (e 2)

/-- Every binary choice in `{1,7,8}` is one of the seven certified digits. -/
theorem blockValue_is_digit :
    ∀ e : BlockChoice, ∃ d : Fin 7, blockValue e = digitValue d := by
  decide

/-- Exact base-19 evaluation of a list of block choices. -/
def evaluateBlocks : List BlockChoice → ℤ
  | [] => 0
  | e :: es => blockValue e + 19 * evaluateBlocks es

theorem evaluateBlocks_mem_language (es : List BlockChoice) :
    Language es.length (evaluateBlocks es) := by
  induction es with
  | nil => exact Language.zero
  | cons e es ih =>
      obtain ⟨d, hd⟩ := blockValue_is_digit e
      simp only [evaluateBlocks, List.length_cons]
      rw [hd]
      exact Language.cons d ih

/-- The actual block-evaluation language has no nonconstant four-term AP. -/
theorem evaluated_blocks_four_ap_constant
    (e₀ e₁ e₂ e₃ : List BlockChoice)
    (hlen₁ : e₁.length = e₀.length)
    (hlen₂ : e₂.length = e₀.length)
    (hlen₃ : e₃.length = e₀.length)
    (hap : FourTermProgression
      (evaluateBlocks e₀) (evaluateBlocks e₁)
      (evaluateBlocks e₂) (evaluateBlocks e₃)) :
    evaluateBlocks e₀ = evaluateBlocks e₁ ∧
      evaluateBlocks e₁ = evaluateBlocks e₂ ∧
      evaluateBlocks e₂ = evaluateBlocks e₃ := by
  apply language_four_ap_constant e₀.length
  · exact evaluateBlocks_mem_language e₀
  · simpa [hlen₁] using evaluateBlocks_mem_language e₁
  · simpa [hlen₂] using evaluateBlocks_mem_language e₂
  · simpa [hlen₃] using evaluateBlocks_mem_language e₃
  · exact hap

/-- Abstract four-AP-freeness of a set of integer coordinates. -/
def FourAPFree (S : Set ℤ) : Prop :=
  ∀ x d : ℤ,
    x ∈ S → x + d ∈ S → x + 2 * d ∈ S → x + 3 * d ∈ S → d = 0

/-!
The next theorem is the exact algebraic morphism behind relation splitting.
The four subset sums are retained as four separately typed membership inputs.
-/
theorem relation_splitting
    (S : Set ℤ) (hfree : FourAPFree S)
    (P₁ P₂ N₁ N₂ : ℤ)
    (hrel : P₁ + 2 * P₂ = N₁ + 2 * N₂)
    (h₀ : P₁ + N₂ ∈ S)
    (h₁ : P₁ + P₂ ∈ S)
    (h₂ : N₁ + N₂ ∈ S)
    (h₃ : N₁ + P₂ ∈ S) :
    P₂ = N₂ ∧ P₁ = N₁ := by
  let d : ℤ := P₂ - N₂
  have hx₁ : P₁ + P₂ = (P₁ + N₂) + d := by
    dsimp [d]
    ring
  have hx₂ : N₁ + N₂ = (P₁ + N₂) + 2 * d := by
    dsimp [d]
    linarith
  have hx₃ : N₁ + P₂ = (P₁ + N₂) + 3 * d := by
    dsimp [d]
    linarith
  have hd : d = 0 := by
    apply hfree (P₁ + N₂) d h₀
    · simpa [hx₁] using h₁
    · simpa [hx₂] using h₂
    · simpa [hx₃] using h₃
  constructor
  · dsimp [d] at hd
    linarith
  · linarith

#print axioms bounded_kernel_mod19
#print axioms digit_second_difference_rigidity
#print axioms language_four_ap_constant
#print axioms evaluated_blocks_four_ap_constant
#print axioms relation_splitting

end ErdosProblem817
